<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard Builder</title>
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://demos.creative-tim.com/soft-ui-dashboard/assets/css/nucleo-icons.css">
    <link rel="stylesheet" href="https://demos.creative-tim.com/soft-ui-dashboard/assets/css/nucleo-svg.css">
    <link rel="stylesheet" href="https://demos.creative-tim.com/soft-ui-dashboard/assets/css/soft-ui-dashboard.min.css?v=1.0.2">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <link rel="stylesheet" href="../assets/css/theme.css">
    <link rel="stylesheet" href="../assets/css/loopple/loopple.css">
    <style>
        /* Định nghĩa các class CSS cho từng trường thông tin */
        .unique-number { font-weight: bold; }
        .full-name { text-transform: uppercase; }
        .identity-number { color: #666; }
        .phone { text-decoration: underline; }
        .gender { color: #00f; }
        .address { font-style: italic; }
        .comorbidities { font-weight: bold; color: #f00; }
        .symptoms { color: #ff7f00; }
        .admission { background-color: #e0e0e0; }
        .location-history { background-color: #c0c0c0; }
        .discharge-date { color: #0f0; }

        /* Định nghĩa các quy tắc CSS để thêm khoảng cách giữa các ô trong bảng */
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: center;
            vertical-align: middle;
            padding: 10px;
        }
        .footer {
            display: flex;
            justify-content: flex-end;
            align-items: center;
            position: fixed;
            bottom: 0;
            right: 0;
            width: 100%;
            
        }

        .nav-footer {
            display: flex;
            list-style: none;
            margin: 0;
            padding: 0;
        }

        .nav-item {
            margin-right: 10px;
        } 
        .more-info-button {
            background-color: #008CBA;
            color: white;
            border: none;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px;
            margin: 4px 2px;
            cursor: pointer;
        }
    </style>
</head>

<body class="mainpage">
     <!-- đọc đoạn nav bar bên phải  -->
  <?php include "../nav.php"; ?>
<!-- ============================================================================== -->
    <div class="main-content" id="panel">
        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 mt-3 shadow-none border-radius-xl" id="navbarTop">
            <div class="container-fluid py-1 px-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                        <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
                        <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Dashboard</li>
                    </ol>
                    <h6 class="font-weight-bolder mb-0">Patient
                    </h6>
                </nav>
               <!-- Đây là đoạn code dành cho searh đã được link  -->
               <?php include "../mod.php"; ?>
            </div>
        </nav>
        <div class="container-fluid pt-3">
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6>Patient table</h6>
                </div>
               
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th>UN</th>
                                    <th>Full Name</th>
                                    <th>Phone</th>
                                    <th>Gender</th>
                                    <th>Address</th>
                                    <th>Hospitalized Date</th>
                                    <th>Discharge Date</th>
                                    <th>More Information</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="unique-number">001</td>
                                    <td class="full-name">John Doe</td>
                                    <td class="phone">123-456-7890</td>
                                    <td class="gender">Male</td>
                                    <td class="address">123 Main St, City</td>
                                    <td class="admission">02-06-2021</td>
                                    <td class="discharge-date">12-06-2021</td>
                                    <td><a class="more-info-button" href="Infor.php">More Info</a></td>
                                </tr>
                                <tr>
                                    <td class="unique-number">002</td>
                                    <td class="full-name">John Doe</td>
                                    <td class="phone">123-456-7890</td>
                                    <td class="gender">Male</td>
                                    <td class="address">123 Main St, City</td>
                                    <td class="admission">02-06-2021</td>
                                    <td class="discharge-date">12-06-2021</td>
                                    <td><a class="more-info-button" href="Infor.php">More Info</a></td>
                                </tr>
                                <tr>
                                    <td class="unique-number">003</td>
                                    <td class="full-name">John Doe</td>
                                    <td class="phone">123-456-7890</td>
                                    <td class="gender">Male</td>
                                    <td class="address">123 Main St, City</td>
                                    <td class="admission">02-06-2021</td>
                                    <td class="discharge-date">12-06-2021</td>
                                    <td><a class="more-info-button" href="Infor.php">More Info</a></td>
                                </tr>
                                <tr>
                                    <td class="unique-number">004</td>
                                    <td class="full-name">John Doe</td>
                                    <td class="phone">123-456-7890</td>
                                    <td class="gender">Male</td>
                                    <td class="address">123 Main St, City</td>
                                    <td class="admission">02-06-2021</td>
                                    <td class="discharge-date">12-06-2021</td>
                                    <td><a class="more-info-button" href="Infor.php">More Info</a></td>
                                </tr>
                                <tr>
                                    <td class="unique-number">005</td>
                                    <td class="full-name">John Doe</td>
                                    <td class="phone">123-456-7890</td>
                                    <td class="gender">Male</td>
                                    <td class="address">123 Main St, City</td>
                                    <td class="admission">02-06-2021</td>
                                    <td class="discharge-date">12-06-2021</td>
                                    <td><a class="more-info-button" href="Infor.php">More Info</a></td>
                                </tr>
                                <tr>
                                    <td class="unique-number">006</td>
                                    <td class="full-name">John Doe</td>
                                    <td class="phone">123-456-7890</td>
                                    <td class="gender">Male</td>
                                    <td class="address">123 Main St, City</td>
                                    <td class="admission">02-06-2021</td>
                                    <td class="discharge-date">12-06-2021</td>
                                    <td><a class="more-info-button" href="Infor.php">More Info</a></td>
                                </tr>
                                

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>


        <!-- Footer -->
    </div>
    <footer class="footer pt-3 pb-4">
        <div class="container-fluid">
            
            <div class="row align-items-center justify-content-lg-between">
                <div class="col-lg-6">
                    <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                        <li class="nav-item">
                            <a href="javascript:;" class="nav-link text-muted" target="_blank">Creative Tim</a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:;" class="nav-link text-muted" target="_blank">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:;" class="nav-link text-muted" target="_blank">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:;" class="nav-link pe-0 text-muted" target="_blank">License</a>
                        </li>
                    </ul>
                </div>
            </div>
            
        </div>
    </footer>
    <script>
        if (document.querySelector("#chart-bars")) {
           	var ctx = document.getElementById("chart-bars").getContext("2d");
           	new Chart(ctx, {
              type: "bar",
              data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                  label: "Sales",
                  tension: 0.4,
                  borderWidth: 0,
                  borderRadius: 4,
                  borderSkipped: false,
                  backgroundColor: "#fff",
                  data: [450, 200, 100, 220, 500, 100, 400, 230, 500],
                  maxBarThickness: 6
                }, ],
              },
              options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                  legend: {
                    display: false,
                  }
                },
                interaction: {
                  intersect: false,
                  mode: 'index',
                },
                scales: {
                  y: {
                    grid: {
                      drawBorder: false,
                      display: false,
                      drawOnChartArea: false,
                      drawTicks: false,
                    },
                    ticks: {
                      suggestedMin: 0,
                      suggestedMax: 500,
                      beginAtZero: true,
                      padding: 15,
                      font: {
                        size: 14,
                        family: "Open Sans",
                        style: 'normal',
                        lineHeight: 2
                      },
                      color: "#fff"
                    },
                  },
                  x: {
                    grid: {
                      drawBorder: false,
                      display: false,
                      drawOnChartArea: false,
                      drawTicks: false
                    },
                    ticks: {
                      display: false
                    },
                  },
                },
              },
            });
        
           };
           if (document.querySelector("#chart-line")) {
           	var ctx2 = document.getElementById("chart-line").getContext("2d");
           	var gradientStroke1 = ctx2.createLinearGradient(0, 230, 0, 50);
           	gradientStroke1.addColorStop(1, "rgba(203,12,159,0.2)");
           	gradientStroke1.addColorStop(0.2, "rgba(72,72,176,0.0)");
           	gradientStroke1.addColorStop(0, "rgba(203,12,159,0)");
           	var gradientStroke2 = ctx2.createLinearGradient(0, 230, 0, 50);
           	gradientStroke2.addColorStop(1, "rgba(20,23,39,0.2)");
           	gradientStroke2.addColorStop(0.2, "rgba(72,72,176,0.0)");
           	gradientStroke2.addColorStop(0, "rgba(20,23,39,0)");
           	new Chart(ctx2, {
              type: "line",
              data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                    label: "Mobile apps",
                    tension: 0.4,
                    borderWidth: 0,
                    pointRadius: 0,
                    borderColor: "#cb0c9f",
                    borderWidth: 3,
                    backgroundColor: gradientStroke1,
                    fill: true,
                    data: [50, 40, 300, 220, 500, 250, 400, 230, 500],
                    maxBarThickness: 6
        
                  },
                  {
                    label: "Websites",
                    tension: 0.4,
                    borderWidth: 0,
                    pointRadius: 0,
                    borderColor: "#3A416F",
                    borderWidth: 3,
                    backgroundColor: gradientStroke2,
                    fill: true,
                    data: [30, 90, 40, 140, 290, 290, 340, 230, 400],
                    maxBarThickness: 6
                  },
                ],
              },
              options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                  legend: {
                    display: false,
                  }
                },
                interaction: {
                  intersect: false,
                  mode: 'index',
                },
                scales: {
                  y: {
                    grid: {
                      drawBorder: false,
                      display: true,
                      drawOnChartArea: true,
                      drawTicks: false,
                      borderDash: [5, 5]
                    },
                    ticks: {
                      display: true,
                      padding: 10,
                      color: '#b2b9bf',
                      font: {
                        size: 11,
                        family: "Open Sans",
                        style: 'normal',
                        lineHeight: 2
                      },
                    }
                  },
                  x: {
                    grid: {
                      drawBorder: false,
                      display: false,
                      drawOnChartArea: false,
                      drawTicks: false,
                      borderDash: [5, 5]
                    },
                    ticks: {
                      display: true,
                      color: '#b2b9bf',
                      padding: 20,
                      font: {
                        size: 11,
                        family: "Open Sans",
                        style: 'normal',
                        lineHeight: 2
                      },
                    }
                  },
                },
              },
            }); 
           };
    </script>
    <script src="../assets/js/loopple/loopple.js"></script>
</body>